[package]
name = "rustytasks"
version = "0.1.0"
edition = "2021"

[dependencies]
automerge = "0.6.0"
serde = "1.0.219"
clap = { version = "4.5.32", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
serde_json = "1.0.140"
base64 = "0.22.1"
rand = "0.8.5"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
sha2 = "0.10.8"
rand_core = "0.6.4"